# fly.toml app configuration file for loki-dashboard
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "loki-dashboard"
primary_region = "lax"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  # Uses local Dockerfile when deploying from this directory
  # For monorepo deployment, use: dockerfile = "../loki/Dockerfile.dashboard"
  dockerfile = "Dockerfile"
  [build.args]
    VITE_AUTH_EMAIL = "yurlovandrew@gmail.com"
    VITE_AUTH_PASSWORD = "Sn0wd@miz120356"

[env]
  PORT = "80"
  NODE_ENV = "production"

[[services]]
  protocol = "tcp"
  internal_port = 80
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/health"
    protocol = "http"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

# Optional: Add these sections if needed
# [mounts]
#   source = "data"
#   destination = "/data"

# [metrics]
#   port = 9091
#   path = "/metrics"
